version: "3"
services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_db:fast_table
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fast_table

networks:
  default:
    name: fastapi

volumes:
  postgres_data:
