# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "fastapi"

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fastapi"
    dns_sd_configs:
      - names: ["fastapi"]
        port: 8000
        type: A
        refresh_interval: 5s

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
